### ISSUE TITLE
Support for Datacite fundingReferences

### ISSUE THREAD

**Issue by ajnyga** [ajnyga/funding#18] opened 2017-09-29 07:36 UTC
After changing the database model according to this issue #16 we can save different kinds of funding data.

https://schema.datacite.org/meta/kernel-4.0/example/datacite-example-fundingReference-v.4.0.xml

```
<fundingReferences>
<fundingReference>
<funderName>European Commission</funderName>
<funderIdentifier funderIdentifierType="Crossref Funder ID">http://doi.org/10.13039/501100000780</funderIdentifier>
<awardNumber awardURI="http://cordis.europa.eu/project/rcn/100180_en.html">282625</awardNumber>
<awardTitle>MOTivational strength of ecosystem services and alternative ways to express the value of BIOdiversity</awardTitle>
</fundingReference>
</fundingReferences>
```

**CrossRef**| |**Datacite**| |**OpenAIRE**
:-----:|:-----:|:-----:|:-----:|:-----:
funder_identifier|=|funderIdentifier|=|missing
funder_name|=|funderName|=|Funder*
award_number|=|awardNumber|=|projectID**
missing|=|awardTitle|=|ProjectName
missing|=|awardURI|=|missing
missing|=|missing|=|ProjectAcronym
missing|=|missing|=|FundingProgramme***

\* Only two options:   European Commission (EC) or Wellcome Trust (WT)? For OAI the acronyms are   used.
** Not sure if the projectID is/can be   the exact same thing?
*** only two options: FP7 and H2020?
 
Sources:
https://support.crossref.org/hc/en-us/articles/214360746-Funding-data-overview
https://guidelines.openaire.eu/en/latest/literature/field_projectid.html
https://schema.datacite.org/meta/kernel-4.0/

**Comment by bozana** [comment] 2017-10-16 15:33
In order to add this to the DataCite export we will first need to support the newest DataCite metadata schema 4. The only problem is the required `resourceType` element and `resourceTypeGeneral` attribute. And the problem is only for supplementary files because they do not have it currently. For resourceType we could use the Genre name, but I am not sure what to use for resourceTypeGeneral except of the very wide "Dataset" term. I will ask DataCite, but if we do not manage to implement this for the coming release (this week) maybe to defer also this issue to the next OJS 3.1.1 release?

**Comment by bozana** [comment] 2017-10-16 15:59
Oh, I've just seen that also an empty element is OK, i.e. something like: `<resourceType resourceTypeGeneral="Dataset"/>`. I believe we can use that well for supplementary files :-) Or maybe even: `<resourceType resourceTypeGeneral="Dataset">Supplementary Resource</resourceType>`

**Comment by bozana** [comment] 2017-10-19 15:26
@ajnyga, do you think we should consider the funding data when exporting/registering the galleys (and supp files)?

**Comment by bozana** [comment] 2017-10-19 15:38
PR: https://github.com/ajnyga/funding/pull/20

**Comment by bozana** [comment] 2017-10-19 15:40
@ajnyga, I merged my changes -- if you find something wrong I can fix... 
For now, I only add funding data when exporting articles in DataCite. I can add it to galleys too... if needed... -- I am not sure... :-\

**Comment by ajnyga** [comment] 2017-10-19 16:06
@bozana  Great, thanks!

I have no idea. But I would imagine that when exporting galleys the metadata would always include a reference to an article? And if that article has the funder data attached, then Datacite should be able to resolve the funder also for individual galleys?

Also, I realized that I did not touch the crossref export part so it is probably not working at the moment because of the dao and database changes?

**Comment by bozana** [comment] 2017-10-19 16:17
> I have no idea. But I would imagine that when exporting galleys the metadata would always include a reference to an article? And if that article has the funder data attached, then Datacite should be able to resolve the funder also for individual galleys?

Yes. Then maybe just the case when someone is assigning the DOIs only to the galleys (and not to the articles).
And I've just realized that I actually do insert the funding data for galley export. Then I should maybe remove it... Hmmm... :-\

> Also, I realized that I did not touch the crossref export part so it is probably not working at the moment because of the dao and database changes?

I did that, so everything OK :-)

Thanks a lot!!!

**Closed as completed** 2017-10-23 19:48 UTC
